### ISSUE TITLE
Error when contacting DOI query service for publication registration

### ISSUE THREAD

**Issue by medonja** [nfdi4health/ldh#60]
**Describe the bug**
We are trying to register a publication for a study, but we get the following error message: An error has occurred whilst attempting to fetch the requested publication. There was a problem contacting the DOI query service. Please try again later.

![image](https://github.com/user-attachments/assets/84c08baf-8eed-4316-ad8f-9aa5bb11188d)

We tried both entering the DOI as well as a DOI URL, in both cases we get the same error message.
I have attached a relevant screenshot from the error log.
![image](https://github.com/user-attachments/assets/e83d503b-15fd-4980-ab01-0e50bf76de68)

**Comment by fmeineke** [comment]
Full URL or DOI only should work both.
In Leipzig test systems with  https://doi.org/10.1007/s00761-024-01565-4 works as expected.
Probably you did not set "Settings/General Settings/CrossRef API email".  _"When adding a publication from a DOI, an email address is required to use the API. The email address needs registering at http://www.crossref.org/"_

You need to enter any kind of E-Mail here. We used "info@health-atlas.de" - please try! ("registering" probably not necessary - fake E-Mail work too)
