### ISSUE TITLE
User Guide in Github wiki not accessible

### ISSUE THREAD

**Issue by Mijar007** [nfdi4health/ldh#66]
**Describe the bug**
The user guide in the wiki is not accessible (https://github.com/nfdi4health/ldh/wiki/UserGuide/index.md)
The following message appears after clicking the link: `You do not have permission to update this wiki`.

**To Reproduce**
1. Go to https://github.com/nfdi4health/ldh/wiki
2. Click on 'User Guide'
3. See error

**Expected behavior**
Seeing the user guide

**Comment by ReneHaensel** [comment]
This was just a testing relique. Please use https://nfdi4health.github.io/ldh-deployment/ for the wiki

**Comment by Mijar007** [comment]
Thank you. I checked the wiki and I think it has to be improved.
Even if its in German, you should use the terms used in the LDHs. E.g. https://nfdi4health.github.io/ldh-deployment/UserGuide/isa_struct.html: you should add the terms "Clinical Trial", "Sub Study" and Resource.
