### ISSUE TITLE
ISA structure with trial project as origin

### ISSUE THREAD

**Issue by Mijar007** [nfdi4health/ldh#70]
A suggestion regarding the ISA structure.
Right now, the structure starts at the level of a clinical trial in a trial project. This is fine if you have several clinical trials on the same topic.
However, if your clinical trial is not part of a larger project, you will need to add another page with no new information.
I think the trial project site is the landing page of your study. So it should contain already the meta data of the clinical trial (MDS3).
Now, what to add to the page 'clinical trial', which you are forced to add, if you want to add a method.
In my opinion, it should be possible to add a sub-study directly to a trial project to avoid empty pages.

**Comment by Mijar007** [comment]
I think it would also be good to add the Snapshot-function to the trial project level

**Comment by fmeineke** [comment]
We support both models; programs/projects only or programs/projects/ISA. We currently recommend programs/projects and ISA enabled, whereby projects can also contain the MDS. Changeover is under Server Settings / If you really want ISA, then see https://isa-specs.readthedocs.io/en/latest/isamodel.html 
Features:
![image](https://github.com/user-attachments/assets/593b5b32-fea8-4b5d-9450-04fa7b44a33a)
