### ISSUE TITLE
Question: What is a Programmadministrator?

### ISSUE THREAD

**Issue by Mijar007** [nfdi4health/ldh#71]
In the user guide the role of a Programmadministrator is listed: https://nfdi4health.github.io/ldh-deployment/UserGuide/roles.html.
However I cannot find this role in the LDH. Does this role really exists?

**Comment by ReneHaensel** [comment]
You can activate the Programms option in the admin panel.
![programms](https://github.com/user-attachments/assets/0b62c723-be30-48c7-b2e0-975e38598ca7)

**Comment by Mijar007** [comment]
Thank you for your answer. However, I cannot find this option. We updated the LDH to the latest version last week.
![Bildschirmfoto 2024-12-02 um 10 50 17](https://github.com/user-attachments/assets/24644401-01a0-4d6b-89d0-6257c25a3a70)
![image](https://github.com/user-attachments/assets/a5e7a3d3-92cb-4490-a0b3-352cb87b1d0f)
![image](https://github.com/user-attachments/assets/9e4165fd-7eb0-4d4f-95f0-59102582ac2e)
![image](https://github.com/user-attachments/assets/5b74f140-2779-40f6-b6a7-b97070f35bbe)

**Comment by Mijar007** [comment]
I found the option. It is not called 'Programmes', but 'Sponsors'.
![image](https://github.com/user-attachments/assets/7cc0e935-0f1a-4248-820a-2ac0dad649a6)
Please keep the terminology in the user guide consistent with the program.

**Comment by fmeineke** [comment]
Whether sponsor or program (standard) depends on the local translation / adaptation (in this case: [clinical-trials.en.yml).  The documentation is always written for the standard.
