### ISSUE TITLE
Modify some user rights

### ISSUE THREAD

**Issue by Mijar007** [nfdi4health/ldh#72]
~~The user guide lists the right of several roles: https://nfdi4health.github.io/ldh-deployment/UserGuide/roles.html
However I think you should add two roles to the table, the SEEK-admin and the NFDI4Health PI.~~

I also think you should modify some rights for a few roles:
- I noticed that the SEEK-admin does not have every right. I tried to edit a publication of a project and could not do it. The publication was added by another active user. After adding myself as Trial Project administrator, I could edit it. On that note, maybe you can give the SEEK-Admin directly the rights to do it, since he can already do it with this workaround. 
-  Based on my observation, the NFDI4Health PI has the same rights as a normal user. This is not intuitive, since from my point of view, the PI is the one responsible for a project and should therefore have the mightiest role in the project. Otherwise, make it clear, that it is just a representative role.
- I noticed that normal user in a project have the "Publish to NFDI4Health GCHSH"-option. I think this option should be limited to project administrators and PIs.

**Comment by fmeineke** [comment]
Please split your topics... this answer refers to the first topic:

- This is by design, not to accidentally change content as an admin.
- there is an option for admins to act as another user; this option must be enabled - this is only possible from the command line (dive into docker container seek): 

```
bundle exec rails c
Loading production environment (Rails 5.2.4.6)
irb(main):001:0> Seek::Config.admin_impersonation_enabled
=> false
irb(main):002:0> Seek::Config.admin_impersonation_enabled = true
=> true
```
