### ISSUE TITLE
Add two roles to rights table in user guide

### ISSUE THREAD

**Issue by Mijar007** [nfdi4health/ldh#73]
The user guide lists the right of several roles: https://nfdi4health.github.io/ldh-deployment/UserGuide/roles.html
However I think you should add two roles to the table, the SEEK-admin and the NFDI4Health PI.
That way it is clear what every role can do.

Based on my observation, the NFDI4Health PI has the same rights as a normal user and the SEEK-admin is not omnipotent.

**Comment by fmeineke** [comment]
NFDI4Health PI (Standard: PAL - this is just localization - as PAL is not really used in clinical context; the "NFDI4Health" is just the plattform name) is rather used as documentation. The PI/PAL has no additional rights - must only be a Person (not compelling a User). The PI/PAL does not even have to know / be in  contact with the LDH/Seek.
